#+TITLE: org-mode

[[http://orgmode.org][官网]]

[[https://github.com/lsytj0413/learn-note/blob/master/text/org.pdf][完全版使用手册]]

[[https://github.com/lsytj0413/learn-note/blob/master/text/orgguide.pdf][简明版使用手册]]

* 简单操作

** 标题

文章中的标题可以通过 #+TITLE: 来设置标题, 例如:

#+BEGIN_EXAMPLE
#+TITLE: org-mode
#+END_EXAMPLE

正文中的标题可以通过星号 * 来设置, 星号后包含一个空格, 然后输入标题文本. 一个星号表示一级标题, 两个表示二级标题, 最多十个.

#+BEGIN_EXAMPLE
* 一级标题
** 二级标题
******** 八级标题
#+END_EXAMPLE

** 段落

在 org-mode 中, 如果你需要换行, 可以使用回车两次的方式, 回车一次仅仅是在中间添加一个空格. 也可以在需要换行的地方输入 \\\\.

#+BEGIN_EXAMPLE
段落一

段落二\\
段落三
#+END_EXAMPLE

** 字体

在 org-mode 中, 可以设置字体的效果.

#+BEGIN_EXAMPLE
*粗体*
/斜体/
+删除线+
_下划线_
下标: H_2 O
上标: E=mc^2
等宽字: =git=
#+END_EXAMPLE

效果如下:

*粗体*

/斜体/

+删除线+

_下划线_

下标: H_2 O

上标: E=mc^2

等宽字: =git=

** 列表

列表包括无序列表, 有序列表以及描述列表, 其中无序列表使用 "-", "+" 或者 "*" 开头, 有序列表使用 "1." 或者 "1)" 开头, 描述列表用 "::" 开头.

#+BEGIN_EXAMPLE
**** Lord of the Rings
   My favorite scenes are (in this order)
   1. The attack of the Rohirrim
   2. Eowyn's fight with the witch king
      + this was already my favorite scene in the book
      + I really like Miranda Otto.
   3. Peter Jackson being shot by Legolas
      - on DVD only
      He makes a really funny face when it happens.
ORG-LIST-END-MARKER
   But in the end, no individual scenes matter but the film as a whole.
   Important actors in this film are:
   - Elijah Wood :: He plays Frodo
   - Sean Austin :: He plays Sam, Frodo's friend.  I still remember
     him very well from his role as Mikey Walsh in The Goonies.
ORG-LIST-END-MARKER
#+END_EXAMPLE

显示效果如下:

**** Lord of the Rings
     My favorite scenes are (in this order)
   1. The attack of the Rohirrim
   2. Eowyn's fight with the witch king
      + this was already my favorite scene in the book
      + I really like Miranda Otto.
   3. Peter Jackson being shot by Legolas
      - on DVD only
      He makes a really funny face when it happens.
   

   But in the end, no individual scenes matter but the film as a whole.
   Important actors in this film are:
   - Elijah Wood :: He plays Frodo
   - Sean Austin :: He plays Sam, Frodo's friend.  I still remember
     him very well from his role as Mikey Walsh in The Goonies.

常用的列表和标题快捷键如下表:

#+CAPTION: 快捷键说明表
| 快捷键         | 说明                                                     |
|----------------+----------------------------------------------------------|
| 折叠类快捷键   |                                                          |
| S-TAB          | 循环切换整个文档的大纲状态, 即折叠, 打开下一级, 打开全部 |
| TAB            | 循环切换光标所在的大纲状态                               |
| 移动快捷键     |                                                          |
|----------------+----------------------------------------------------------|
| C-c C-n/p      | 移动到下/上一个标题                                      |
| C-c C-f/b      | 跳到同一个级别的下/上一个标题                            |
| C-c C-u        | 跳到上一级标题                                           |
| C-c C-j        | 切换到大纲预览状态                                       |
|----------------+----------------------------------------------------------|
| 编辑快捷键     |                                                          |
| M-RET          | 插入一个同级别的标题                                     |
| M-S-RET        | 插入一个同级别的TODO标题                                 |
| M-left/right   | 将当前标题升/降级                                        |
| M-S-left/right | 将当前子树升/降级                                        |
| M-S-up/down    | 将当前子树上/下移动                                      |
| C-c *          | 将本行设置为b标题或正文                                  |
| C-c C-w        | 将子树或者区域移动到另一个标题处, 跨缓冲区               |
| C-c C-x b      | 在新缓冲区显示当前分支                                   |
| C-c /          | 只列出包含搜索结果的大纲并高亮, 支持多种搜索方式         |

** 元数据

*** 内容元数据

org-mode 中的内容元数据包含以下几种:

#+BEGIN_EXAMPLE
s    #+begin_src ... #+end_src
e    #+begin_example ... #+end_example    : 单行的例子以冒号开头
q    #+begin_quote ... #+end_quote    通常用于引用, 与默认格式相比左右都会留出缩进
v    #+begin_verse ... #+end_verse    默认内容不换行, 需要留出空行才换行
c    #+begin_center ... #+end_center
l    #+begin_latex ... #+end_latex
L    #+latex:
h    #+begin_html ... #+end_html
H    #+html:
a    #+begin_ascii ... #+end_ascii
A    #+ascii:
i    #+index: line
I    #+include: line
#+END_EXAMPLE

- 代码

在上面第一列中的单个字母为快捷键字母, 如输入一个 <s , 然后按下 TAB 键就会展开为:

#+BEGIN_EXAMPLE
#+BEGIN_SRC 

#+END_SRC
#+END_EXAMPLE

对代码块还可以加入一些参数, 例如:

#+BEGIN_EXAMPLE
#+BEGIN_SRC c -n -t -h 7 -w 40

#+END_SRC
其中:
c 表示d代码块使用的语言
-n 表示显示行号
-t 表示清除格式
-h 7 表示设置高度为7
-w 40 表示设置宽度为40
#+END_EXAMPLE

- 注释

以 # 号开头的行被看作注释, 不会被导出区块, 注释采用的写法如下:

#+BEGIN_EXAMPLE
#+BEGIN_COMMENT
    块注释
    ...
#+END_COMMENT
#+END_EXAMPLE

- 表格和图片

对于表格和图片, 可以在前面增加标题和标签的说明, 以方便交叉引用.

#+BEGIN_EXAMPLE
#+CAPTION: This is the caption for the next table (or link)
#+END_EXAMPLE

在需要的地方可以通过如下方式引用:

#+BEGIN_EXAMPLE
\ref{table1}
#+END_EXAMPLE

- 嵌入 html

对于导出 html 及发布, 嵌入 html 代码是一个有用的特性. 例如使用下面的例子格式化代码块:

#+BEGIN_EXAMPLE
#+BEGIN_HTML:
  <div class="cnblogs_Highlighter">
  <pre class="brush:cpp">
  int main()
  {
    return 0;
  }
  </pre>
  </div>
#+END_EXAMPLE

相当于在网页中插入 C++ 代码块.

- 包含文件

在导出文档时可以包含其他文件中的内容, 例如包含 .emacs 文件:

#+BEGIN_EXAMPLE
#+INCLUDE: "~/.emacs" src emacs-lisp
#+END_EXAMPLE

可选的第二个参数是组织方式, 例如 quote, example 或 src 等; 如果是 src 则第三个参数用来表示格式化语言. 组织方式是可选的, 如果不给处则会被当作 Org 模式的文本处理. 用 C-c 可以访问包含的文件.

*** 文档元数据

#+CAPTION: 文档元数据表
| 元数据    | 说明                          |
|-----------+-------------------------------|
| H:        | 标题层数                      |
| num:      | 章节(标题)是否自动编号        |
| toc:      | 是否生成索引                  |
| creator:  | 是否生成 "create by emacs..." |
| LINKUP:   | UP: 链接                      |
| LINKHOME: | HOME: 链接                    |

** 表格

*** 建立和操作表格

在 org-mode 中, 可以通过文本的方式描述表格. 在某一行顶格的位置输入 |, 然后输入第一行第一列的内容, 再输入 |, 以此类推. 当第一行输入完成后按下 TAB, org-mode 会自动把当前行对齐, 
然后为你创造出表格的下一行. 用 TAB 和 S+TAB 可以在表格中正向或反向移动.

#+BEGIN_EXAMPLE
#+CAPTION: 表格的标题
| 1 | one |
| 2 | two |
| 3 | This is a long chunk of text |
| 4 | four |
#+END_EXAMPLE

如果表格的某一项特别的长, 可以在任意一个表格的空白项输入数字来限制其所在列的长度. 例如:

#+BEGIN_EXAMPLE
|   | <6>    |
| 1 | one    |
| 2 | two    |
| 3 | This=> |
| 4 | four   |

这会限制第二列的长度不超过6, 超过的部分会被隐藏. 可以在表格项中输入 C-c 编辑被隐藏的内容, 或者输入 C-c C-c 来将内容隐藏起来.
#+END_EXAMPLE

也可以在表格的某两行中输入 |- , 然后按下 TAB, org-mode 会创造出一个分割行.

#+BEGIN_EXAMPLE
|   | <6>    |
|---+--------|
| 1 | one    |
| 2 | two    |
| 3 | This=> |
| 4 | four   |
#+END_EXAMPLE

*** 快捷键

常用的表格快捷键如下表:

#+CAPTION: 快捷键说明表
| 快捷键         | 说明                           |
|----------------+--------------------------------|
| 整体区域       |                                |
| C-c 竖线       | 创建或者转换为表格             |
| C-c C-c        | 调整表格, 不移动光标           |
| TAB            | 移动到下一格, 必要时新建一行   |
| S-TAB          | 移动到上一格                   |
| RET            | 移动到下一行, 必要时新建一行   |
| 编辑行列       |                                |
|----------------+--------------------------------|
| M-left/right   | 移动列                         |
| M-up/down      | 移动行                         |
| M-S-left/right | 删除/插入列                    |
| M-S-up/down    | 删除/插入行                    |
| C-c -          | 添加水平分割线                 |
| C-c RET        | 添加水平分割线并跳到下一行     |
| C-c ^          | 根据当前列排序, 可选择排序方式 |

*** 表格中的计算

假设有如下一张价格表:

| 数量 | 单价 | 总额 |
|------+------+------|
|    2 | 3.45 |      |
|    4 | 4.34 |      |
|    5 | 3.44 |      |
|    5 |  5.6 |      |

可以在最后一行之后输入如下字符, 然后按下 C-c C-c 进行计算:

#+BEGIN_EXAMPLE
| 数量 | 单价 |  总额 |
|------+------+-------|
|    2 | 3.45 |   6.9 |
|    4 | 4.34 | 17.36 |
|    5 | 3.44 |  17.2 |
|    5 |  5.6 |   28. |
#+TBLFM: $3=$1*$2
#+END_EXAMPLE

在 Spacemacs 中, 可以在对应行按下 [SPC m t r] 或者 [SPC m t e] 进行计算.

** 链接

*** 自动链接

对于符合链接规则的内容, org-mode 会自动将其视为链接, 包括文件, 网页等:

#+BEGIN_EXAMPLE
http://www.astro.uva.nl/~dominik            on the web
file:/home/dominik/images/jupiter.jpg       file, absolute path
/home/dominik/images/jupiter.jpg            same as above
file:papers/last.pdf                        file, relative path
file:projects.org                           another Org file
docview:papers/last.pdf::NNN                open file in doc-view mode at page NNN
id:B7423F4D-2E8A-471B-8810-C40F074717E9     Link to heading by ID
news:comp.emacs                             Usenet link
mailto:adent@galaxy.net                     Mail link
vm:folder                                   VM folder link
vm:folder#id                                VM message link
wl:folder#id                                WANDERLUST message link
mhe:folder#id                               MH-E message link
rmail:folder#id                             RMAIL message link
gnus:group#id                               Gnus article link
bbdb:R.*Stallman                            BBDB link (with regexp)
irc:/irc.com/#emacs/bob                     IRC link
info:org:External%20links                   Info node link (with encoded space)
#+END_EXAMPLE

对于文件链接, 可以用 :: 后面增加定位符的方式链接到文件的特定位置, 定位符可以是行号或搜索选项:

#+BEGIN_EXAMPLE
file:~/code/main.c::255                     进入到 255 行
file:~/xx.org::My Target                    找到目标‘<<My Target>>’
file:~/xx.org/::#my-custom-id               查找自定义 id 的项
#+END_EXAMPLE

*** 手动链接

可以手动插入链接文本:

#+BEGIN_EXAMPLE
[[link][description]]
[[link]]
#+END_EXAMPLE

*** 内部链接

内部链接就类似于 HTML 的锚点, 可以实现在一个文档内部的跳转:

#+BEGIN_EXAMPLE
#<<target>> (这里我把锚点设置到*连接*这一部分开始处，大家可以点击下面效果中两个连接试试效果)
如下方式可以设置到target的链接：
[[target]] 或 [[target][猛击锚点]]
#+END_EXAMPLE

** 注脚

在 org-mode 中, 可以为文章添加注脚. 注脚的格式有两种: 一是方括号 + 数字, 二是 方括号 + fn + 数字. 例如在文档中写下以下两句话:

The Org homepage[1] now looks a lot better than it used to. The Org homepage[2] now looks a lot better than it used to.

然后在文档接下来的地方顶格写下:

[1] The link is: http://orgmode.org
[fn:orghome] The link is: http://orgmode.org

按下 C-c C-c 可以在注脚和使用处互相切换.
